# Generated by Django 3.2.8 on 2021-11-16 07:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(choices=[('Senior Role', 'Senior Role'), ('Junior Role', 'Junior Role'), ('Fresher', 'Fresher'), ('Intern', 'Intern')], max_length=20, null=True)),
                ('min_experience', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True)),
                ('max_experience', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, null=True)),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', ckeditor.fields.RichTextField(max_length=1000)),
                ('loction', models.CharField(max_length=20)),
                ('post_date', models.DateField()),
                ('company_introduction', ckeditor.fields.RichTextField(max_length=1000, null=True)),
                ('experience_reguired', ckeditor.fields.RichTextField(max_length=1000, null=True)),
                ('eligibility_criteria', ckeditor.fields.RichTextField(max_length=1000, null=True)),
                ('job_full_description', ckeditor.fields.RichTextField(max_length=1000, null=True)),
                ('roles_and_responsibilities', ckeditor.fields.RichTextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application_forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('li_link', models.URLField()),
                ('git_link', models.URLField(null=True)),
                ('cv_file', models.FileField(max_length=254, null=True, upload_to='resume')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careers')),
            ],
        ),
    ]
