# Generated by Django 3.2.8 on 2021-11-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_forms',
            name='job_id',
        ),
        migrations.AddField(
            model_name='application_forms',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
