# Generated by Django 3.2.8 on 2021-11-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_auto_20211116_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_forms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
