# Generated by Django 3.2.8 on 2021-11-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_auto_20211125_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careers',
            old_name='experience_reguired',
            new_name='experience_required',
        ),
    ]
