# Generated by Django 3.2.9 on 2021-12-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_rename_experience_reguired_careers_experience_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers',
            name='experience_required',
        ),
    ]
