# Generated by Django 3.2.9 on 2021-12-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_remove_careers_experience_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_forms',
            name='li_link',
            field=models.URLField(null=True),
        ),
    ]
