# Generated by Django 3.2.9 on 2021-12-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_auto_20211206_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_forms',
            name='git_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application_forms',
            name='li_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
