# Generated by Django 3.2.9 on 2021-12-06 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0011_auto_20211206_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_forms',
            name='cv_file',
            field=models.FileField(upload_to='resume', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
