# Generated by Django 3.1.7 on 2021-12-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0012_alter_application_forms_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_forms',
            name='git_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application_forms',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='application_forms',
            name='li_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
